### ISSUE TITLE
version resolver is not applied to build script dependencies

### ISSUE THREAD

**Issue by icecrystal23** [sarhanm/gradle-versioner#2]

**Comment by sarhanm** [comment]
Adding a bit of color to the bug and I'll keep this open in hopes that gradle will provide early access for the plugin. 

This is currently not possible because gradle does not execute plugins early enough to influence those resolutions.  Putting the plugin into the init script won't help you get early enough in the process either.

**Comment by sarhanm** [comment]
I found a way to do this!

If you create an initscript plugin, you can do the following

```
def manifestOptions = {set this up yourself or set to null}
VersionResolverInternal resolver = new VersionResolverInternal(project, manifestOptions,
                    project.buildscript.configurations, project.buildscript.repositories, null)

project.buildscript.configurations.all { Configuration c ->
    if (c.name != "versionManifest")
        c.resolutionStrategy.eachDependency(resolver)
}
```

VersionResolverInternal is an internal implementation, so before others should use this, we need to promote it to a public impl.

**Comment by sarhanm** [comment]
Documented here: https://github.com/sarhanm/gradle-versioner/wiki/Version-Manifest#defining-version-manifest-for-buildscript-dependencies
